name: Deploy Ephemeral Environment

on:
  push:
    branches:
      - 'feature/**'

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.10.5

jobs:
  deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="branch_name=${GITHUB_ENV.BRANCH_NAME}" \
            -var="name=${GITHUB_ENV.BRANCH_NAME}" \
            -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan || exit 1