name: Deploy Ephemeral Environment

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name for the environment to destroy'
        required: true
        type: string


env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.10.5

jobs:
  deploy:
    if: contains(fromJson('["push", "workflow_dispatch"]'), github.event_name)
    name: Deploy Environment
    uses: ./.github/workflows/_deploy-template.yml
    with:
      branch: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref_name }}
    secrets: inherit

  destroy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Destroy Environment
    uses: ./.github/workflows/_destroy-template.yml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
    secrets: inherit