name: Deploy Ephemeral Environment

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types: [closed]


env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.10.5

jobs:
  deploy:
    if: github.event_name == 'push'
    name: Deploy Environment
    uses: ./.github/workflows/_deploy-template.yml
    with:
      branch: ${{ github.ref_name }}
    secrets: inherit

  destroy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Destroy Environment
    uses: ./.github/workflows/_destroy-template.yml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
    secrets: inherit
