name: Deploy Ephemeral Environment

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to deploy'
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.10.5

jobs:
  deploy-on-push:
    if: github.event_name == 'push'
    name: Deploy on Push
    uses: ./.github/workflows/_deploy-template.yml
    with:
      branch: ${{ github.ref_name }}
    secrets: inherit

  deploy-on-dispatch:
    if: github.event_name == 'workflow_dispatch'
    name: Deploy on Manual Trigger
    uses: ./.github/workflows/_deploy-template.yml
    with:
      branch: ${{ github.event.inputs.branch }}
    secrets: inherit

  destroy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Destroy Environment
    uses: ./.github/workflows/_destroy-template.yml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
    secrets: inherit
