name: Manual Destroy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name for the environment to destroy'
        required: true
        type: string

jobs:
  remote-destroy:
    uses: ./.github/workflows/_destroy-template.yml
    with:
      raw_branch_name: ${{ github.event.inputs.branch }}
    secrets: inherit
